🚀 Redux কখন ব্যবহার করবেন?

React বা Next.js প্রজেক্টে Redux তখনই ব্যবহার করা উচিত যখন আপনার অ্যাপ্লিকেশনের state management বড়, জটিল অথবা অনেক কম্পোনেন্টের মাঝে শেয়ার করতে হয়।

✅ Redux ব্যবহারের উপযুক্ত পরিস্থিতি
1️⃣ বড় অ্যাপ যেখানে অনেক কম্পোনেন্টে একই ডেটা লাগে

যেমন:

User authentication data (token, user info)
Cart data (eCommerce)
Theme mode (dark/light)
Notifications
Global settings

একটি data অনেক জায়গায় দরকার — তখন prop drilling এড়াতে Redux perfect.

2️⃣ যখন state অনেক deep nested হয়ে যায়

একটা কম্পোনেন্ট থেকে নিচের ৫-৬ লেভেলের কম্পোনেন্টে data পাঠাতে গেলে prop drilling ঝামেলাপূর্ণ হয়।
Redux এই সমস্যা সুন্দরভাবে সমাধান করে।

3️⃣ যখন asynchronous data manage করতে হয়

API call data loading, success, error state — এসব manage করা Redux Toolkit দিয়ে খুব সহজ।

4️⃣ Team-based, large-scale project

Redux structure clear:
actions → reducers → store → components
তাই বড় টিমে কাজ করা সহজ হয়ে যায়।

5️⃣ জটিল business logic control করা

যেমন:

বিভিন্ন API call এর পর নির্দিষ্ট action trigger করা

Condition অনুযায়ী multiple reducer update করা

Middleware ব্যবহার করা (logger, thunk, saga)

❌ Redux ব্যবহার না করাই ভালো যখন —
1️⃣ Small / simple project

ছোট portfolio

Simple blog

Static UI
এসবের জন্য Redux অতিরিক্ত ciężal (overkill)।

2️⃣ যখন শুধু ১-২টি জায়গায় state দরকার

মোট ২-৩টি কম্পোনেন্টে data শেয়ার হয় — তখন React useState, useContext যথেষ্ট।

3️⃣ Prisma/Server Actions/Next.js App Router heavy use করলে

Next.js App Router-এ অনেক state server-side থেকে আসে। তখন Redux লাগতেও নাও পারে।

⭐ একটি সহজ সারাংশ:
কখন ব্যবহার করবেন	কখন করবেন না
বড় জটিল প্রজেক্ট	   ছোট simple UI project
অনেক কম্পোনেন্টে shared data	মাত্র ২–৩টি কম্পোনেন্টে data দরকার
Async API state manage করতে	Static content
Prop drilling বেশি হলে	        Lightweight system


#Redux Toolkit 
#Installation
1️⃣ Install Dependencies
npm install @reduxjs/toolkit react-redux
2️⃣ Create a Redux Store
#project root diretory
redux/store.js
--code for store.js--
import { configureStore } from '@reduxjs/toolkit';
import counterReducer from "./counterSlice";
export const store = configureStore({
    reducer: {
        counter: counterReducer,
    }
});

export default store;
redux/counterSlice.js
--code for counterSlice.js--
import { createSlice } from '@reduxjs/toolkit';

const initialState = {
    value: 0,
};

const counterSlice = createSlice({
    name: "counter",
    initialState,
    reducers: {
        increment: (state) => {
            state.value += 1;
        },
        decrement: (state) => {
            state.value -= 1;
        },
        incrementByAmount: (state, action) => {
            state.value += action.payload;
        },
    },
});

export const { increment, decrement, incrementByAmount } = counterSlice.actions;
export default counterSlice.reducer;

#app/layout.js
import "./globals.css";
import Provider from './libs/ReduxProvider';
import {Toaster} from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Toaster position="top-right" />
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}

#app/page.js
'use client';

import { useSelector, useDispatch } from 'react-redux';
import { increment, decrement } from '../store/counterSlice';

export default function HomePage() {
  const count = useSelector((state) => state.counter.value);
  const dispatch = useDispatch();

  return (
    <div className="p-4">
      <h1>Count: {count}</h1>
      <button onClick={() => dispatch(increment())} className="px-4 py-2 bg-blue-500 text-white mr-2">
        Increment
      </button>
      <button onClick={() => dispatch(decrement())} className="px-4 py-2 bg-red-500 text-white">
        Decrement
      </button>
    </div>
  );
}


6️⃣ Optional: TypeScript Support

If using TypeScript, define RootState and AppDispatch for type safety:

// store/index.ts
export type RootState = ReturnType<typeof store.getState>;
export type AppDispatch = typeof store.dispatch;


Then in components:

import { useSelector, useDispatch } from 'react-redux';
import type { RootState, AppDispatch } from '../store';

const count = useSelector((state: RootState) => state.counter.value);
const dispatch = useDispatch<AppDispatch>();

✅ Summary

Create Redux store & slices in store/.

Wrap Provider in app/layout.js.

Mark any component using Redux as 'use client'.

Use useSelector & useDispatch inside client components.

 const res = await dispatch(login({ email, password }));
      if (res.type === "login/rejected") {
        setLoginError(true);
      } 
এই কোডটা Redux Toolkit (createAsyncThunk) ব্যবহার করে login action dispatch করার একটি উদাহরণ। ধাপে ধাপে বাংলায় বুঝিয়ে দিচ্ছি 👇

const res = await dispatch(login({ email, password }));


🔹 এখানে কী হচ্ছে?

login হচ্ছে একটি async thunk action (সাধারণত createAsyncThunk দিয়ে তৈরি)

dispatch(login({ email, password }))
→ লগইন API কল করা হচ্ছে email এবং password পাঠিয়ে

await ব্যবহার করা হয়েছে, কারণ এটি একটি asynchronous request

res এর মধ্যে action-এর result চলে আসে

if (res.type === "login/rejected") {
  setLoginError(true);
}


🔹 এখানে কী চেক করা হচ্ছে?

Redux Toolkit এ createAsyncThunk এর ৩টি অবস্থা থাকে:

login/pending → request চলছে

login/fulfilled → request সফল

login/rejected → request ব্যর্থ (ভুল email/password, server error ইত্যাদি)

res.type === "login/rejected"
→ মানে লগইন ব্যর্থ হয়েছে

setLoginError(true)
→ React state আপডেট করা হচ্ছে
→ UI তে error message দেখানোর জন্য (যেমন: "Invalid email or password")

সহজ ভাষায় সারসংক্ষেপ 🧠

👉 ইউজার লগইন করার চেষ্টা করে
👉 যদি লগইন সফল হয় → কিছুই হবে না
👉 যদি লগইন ব্যর্থ হয় → setLoginError(true) হয়ে error দেখাবে

উদাহরণ UI ব্যবহার
{loginError && (
  <p className="text-red-500">Email অথবা Password ভুল</p>
)}
